// This file is automatically generated by cpp/update-moc.sh

#include "./connector.h"
#include "./moc_connector.cpp"

#include "./govalue.h"
#include "./moc_govalue.cpp"

#include "./idletimer.h"
#include "./moc_idletimer.cpp"
